package cookiesession

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"gohttpauto/internal/db"
)

// Cookie represents a browser cookie in extension export format.
type Cookie struct {
	Domain         string  `json:"domain"`
	ExpirationDate float64 `json:"expirationDate,omitempty"`
	HostOnly       bool    `json:"hostOnly"`
	HTTPOnly       bool    `json:"httpOnly"`
	Name           string  `json:"name"`
	Path           string  `json:"path"`
	SameSite       *string `json:"sameSite"`
	Secure         bool    `json:"secure"`
	Session        bool    `json:"session"`
	StoreID        string  `json:"storeId"`
	Value          string  `json:"value"`
}

// Payload is saved in cookies_json column.
type Payload struct {
	Referer         string   `json:"referer"`
	IncludedFormats []string `json:"includedFormats"`
	Cookies         []Cookie `json:"cookies,omitempty"`
}

// SaveOptions controls which columns are written for a session.
type SaveOptions struct {
	WebsiteID   string
	Referer     string
	Cookies     []Cookie
	Netscape    string
	Header      string
	LocalStorage string
	IndexedDB   string
}

func BuildPayload(referer string, cookies []Cookie) string {
	p := Payload{
		Referer:         referer,
		IncludedFormats: []string{"cookies"},
		Cookies:         cookies,
	}
	b, _ := json.Marshal(p)
	return string(b)
}

func BuildNetscape(cookies []Cookie, comment string) string {
	var sb strings.Builder
	sb.WriteString("# Netscape HTTP Cookie File\n")
	if comment != "" {
		sb.WriteString("# " + comment + "\n")
	}
	sb.WriteString("\n")
	for _, c := range cookies {
		if c.Name == "" {
			continue
		}
		domain := c.Domain
		if domain == "" {
			domain = ".example.com"
		}
		if !strings.HasPrefix(domain, ".") && !c.HostOnly {
			domain = "." + domain
		}
		path := c.Path
		if path == "" {
			path = "/"
		}
		sec := "FALSE"
		if c.Secure {
			sec = "TRUE"
		}
		exp := "0"
		if c.ExpirationDate > 0 {
			exp = fmt.Sprintf("%d", int64(c.ExpirationDate))
		}
		sb.WriteString(fmt.Sprintf("%s\tTRUE\t%s\t%s\t%s\t%s\t%s\n", domain, path, sec, exp, c.Name, c.Value))
	}
	return sb.String()
}

func BuildHeader(cookies []Cookie) string {
	var parts []string
	for _, c := range cookies {
		if c.Name != "" {
			parts = append(parts, fmt.Sprintf("%s=%s", c.Name, c.Value))
		}
	}
	return strings.Join(parts, "; ")
}

func Save(ctx context.Context, opts SaveOptions) error {
	jsonStr := ""
	if len(opts.Cookies) > 0 {
		jsonStr = BuildPayload(opts.Referer, opts.Cookies)
	}
	netscape := opts.Netscape
	if netscape == "" && len(opts.Cookies) > 0 {
		netscape = BuildNetscape(opts.Cookies, "Generated by GoHttpAuto")
	}
	header := opts.Header
	if header == "" && len(opts.Cookies) > 0 {
		header = BuildHeader(opts.Cookies)
	}

	_, err := db.DB.ExecContext(ctx, `
		INSERT INTO shared_sessions
			(website_id, cookies_json, cookies_netscape, cookies_header, local_storage, indexed_db, updated_at)
		VALUES (?, ?, ?, ?, ?, ?, NOW())
		ON DUPLICATE KEY UPDATE
			cookies_json = VALUES(cookies_json),
			cookies_netscape = VALUES(cookies_netscape),
			cookies_header = VALUES(cookies_header),
			local_storage = COALESCE(VALUES(local_storage), local_storage),
			indexed_db = COALESCE(VALUES(indexed_db), indexed_db),
			updated_at = NOW()`,
		opts.WebsiteID,
		nullIfEmpty(jsonStr),
		nullIfEmpty(netscape),
		nullIfEmpty(header),
		nullIfEmpty(opts.LocalStorage),
		nullIfEmpty(opts.IndexedDB),
	)
	return err
}

func nullIfEmpty(s string) sql.NullString {
	if strings.TrimSpace(s) == "" {
		return sql.NullString{}
	}
	return sql.NullString{String: s, Valid: true}
}

// SimpleCookie builds one cookie entry for HTTP-only flows.
func SimpleCookie(domain, name, value string, secure, httpOnly bool, expires time.Time) Cookie {
	sameSite := "lax"
	return Cookie{
		Domain:         domain,
		ExpirationDate: float64(expires.Unix()),
		HostOnly:       false,
		HTTPOnly:       httpOnly,
		Name:           name,
		Path:           "/",
		SameSite:       &sameSite,
		Secure:         secure,
		Session:        false,
		StoreID:        "0",
		Value:          value,
	}
}
