package toolbaazar

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"net/url"
	"regexp"
	"strings"
	"time"

	"gohttpauto/internal/automation/httpclient"
	"gohttpauto/internal/cookiesession"
	"gohttpauto/internal/db"
)

var semrushLinkRE = regexp.MustCompile(`(?i)href=["']([^"']*(?:semrush4\.toolbaazar\.com|toolbaazar\.com)[^"']*)["']`)

func RunSemrush() (string, string) {
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	var username, password string
	err := db.DB.QueryRowContext(ctx,
		`SELECT username, password_enc FROM credentials WHERE website_id='toolbaazar' AND is_enabled=1`).
		Scan(&username, &password)
	if err != nil {
		return "failed", "toolbaazar credentials not found in database"
	}

	client := httpclient.New(60 * time.Second)
	memberURL := "https://app.toolbaazar.com/member"
	loginURL := "https://app.toolbaazar.com/login"
	portalSessionID := "toolbaazar_login"

	if saved, err := cookiesession.Load(ctx, portalSessionID); err == nil && len(saved) > 0 {
		_ = client.SetCookies("https://app.toolbaazar.com/", cookiesession.ToHTTPCookies(saved))
		log.Printf("[Toolbaazar] restored %d portal cookies", len(saved))
	}

	body, status, _, err := client.GET(memberURL, nil)
	if err != nil || status != 200 {
		return "failed", fmt.Sprintf("member page error: %v (status %d)", err, status)
	}
	needsLogin := strings.Contains(strings.ToLower(body), `name="amember_login"`) ||
		strings.Contains(strings.ToLower(body), `id="amember-login"`) ||
		strings.Contains(strings.ToLower(body), `type="password"`)

	if needsLogin {
		form := url.Values{}
		form.Set("amember_login", username)
		form.Set("amember_pass", password)
		form.Set("remember_login", "1")

		finalURL, postBody, _, err := client.POST(loginURL, form.Encode(), map[string]string{
			"Content-Type": "application/x-www-form-urlencoded",
			"Origin":       "https://app.toolbaazar.com",
			"Referer":      memberURL,
		})
		if err != nil || !httpclient.LoginOK(finalURL, postBody) {
			return "failed", "toolbaazar login failed"
		}
		log.Printf("[Toolbaazar] login OK → %s", finalURL)
	}

	if err := savePortalSession(ctx, client, portalSessionID, "https://app.toolbaazar.com/"); err != nil {
		log.Printf("⚠️ [Toolbaazar] portal cookie save failed: %v", err)
	}

	dashBody, _, _, err := client.GET(memberURL, map[string]string{
		"Referer": "https://app.toolbaazar.com/",
	})
	if err != nil {
		return "failed", "dashboard load error: " + err.Error()
	}

	btn := findSemrushLink(dashBody)
	if btn == "" {
		return "failed", "semrush access link not found on dashboard"
	}
	if strings.HasPrefix(btn, "/") {
		btn = "https://app.toolbaazar.com" + btn
	}
	log.Printf("[Toolbaazar] semrush link: %s", btn)

	finalSemURL, _, _, err := client.GET(btn, map[string]string{
		"Referer": memberURL,
	})
	if err != nil {
		return "failed", "semrush access error: " + err.Error()
	}
	if !strings.Contains(strings.ToLower(finalSemURL), "semrush4.toolbaazar.com") {
		log.Printf("⚠️ [Toolbaazar] final URL: %s", finalSemURL)
	}

	cookies := filterSemrushCookies(client.HTTP.Jar, client.Captured)
	if len(cookies) == 0 {
		return "failed", "no valid toolbaazar semrush cookies captured"
	}

	netscape := cookiesession.BuildNetscape(cookies, "Generated by GoHttpAuto Toolbaazar HTTP Engine")
	err = cookiesession.Save(ctx, cookiesession.SaveOptions{
		WebsiteID: "toolbaazar",
		Referer:   "https://semrush4.toolbaazar.com/",
		Cookies:   cookies,
		Netscape:  netscape,
	})
	if err != nil {
		return "failed", "db save error: " + err.Error()
	}

	go uploadCookies(cookies)
	return "success", fmt.Sprintf("HTTP automation complete — %d cookies captured", len(cookies))
}

func findSemrushLink(html string) string {
	if m := semrushLinkRE.FindStringSubmatch(html); len(m) > 1 {
		return strings.TrimSpace(m[1])
	}
	return ""
}

func filterSemrushCookies(jar http.CookieJar, captured []*http.Cookie) []cookiesession.Cookie {
	seen := map[string]bool{}
	var out []cookiesession.Cookie
	expires := time.Now().Add(365 * 24 * time.Hour)

	add := func(c *http.Cookie) {
		if c == nil || c.Name == "" {
			return
		}
		key := c.Name + "|" + c.Value
		if seen[key] {
			return
		}
		seen[key] = true

		exp := expires
		if !c.Expires.IsZero() {
			exp = c.Expires
		}
		out = append(out, cookiesession.SimpleCookie(
			".toolbaazar.com", c.Name, c.Value, c.Secure, c.HttpOnly, exp,
		))
	}

	for _, c := range captured {
		if c == nil {
			continue
		}
		host := strings.ToLower(c.Domain)
		if strings.Contains(host, "toolbaazar.com") {
			add(c)
		}
	}
	for _, host := range []string{
		"https://semrush4.toolbaazar.com/",
		"https://app.toolbaazar.com/",
	} {
		u, _ := url.Parse(host)
		for _, c := range jar.Cookies(u) {
			cp := *c
			cp.Domain = ".toolbaazar.com"
			add(&cp)
		}
	}
	return out
}

func savePortalSession(ctx context.Context, client *httpclient.Client, websiteID, referer string) error {
	raw, err := client.CookiesFor(referer)
	if err != nil {
		return err
	}
	cookies := make([]cookiesession.Cookie, 0, len(raw))
	for _, c := range raw {
		if c == nil || c.Name == "" {
			continue
		}
		exp := c.Expires
		if exp.IsZero() {
			exp = time.Now().Add(24 * time.Hour)
		}
		cookies = append(cookies, cookiesession.SimpleCookie(c.Domain, c.Name, c.Value, c.Secure, c.HttpOnly, exp))
	}
	if len(cookies) == 0 {
		return nil
	}
	return cookiesession.Save(ctx, cookiesession.SaveOptions{
		WebsiteID: websiteID,
		Referer:   referer,
		Cookies:   cookies,
	})
}

func uploadCookies(cookies []cookiesession.Cookie) {
	payload, _ := json.Marshal(cookies)
	data := url.Values{}
	data.Set("cookies", string(payload))
	data.Set("update", "Update Cookies")
	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.PostForm("https://refs.1clkaccess.store/tbsm1.php", data)
	if err != nil {
		log.Printf("⚠️ [Toolbaazar] tbsm1 upload failed: %v", err)
		return
	}
	resp.Body.Close()
}
