package gfx

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/proto"
)

// CookieJSON matches Chrome extension export format used by GFX payloads.
type CookieJSON struct {
	Domain         string  `json:"domain"`
	ExpirationDate float64 `json:"expirationDate,omitempty"`
	HostOnly       bool    `json:"hostOnly"`
	HttpOnly       bool    `json:"httpOnly"`
	Name           string  `json:"name"`
	Path           string  `json:"path"`
	SameSite       string  `json:"sameSite,omitempty"`
	Secure         bool    `json:"secure"`
	Session        bool    `json:"session"`
	StoreId        *string `json:"storeId"`
	Value          string  `json:"value"`
}

func formatCookieForExtension(c *proto.NetworkCookie) CookieJSON {
	sameSite := ""
	if c.SameSite != "" {
		if c.SameSite == proto.NetworkCookieSameSiteNone {
			sameSite = "no_restriction"
		} else {
			sameSite = strings.ToLower(string(c.SameSite))
		}
	}

	session := c.Expires == -1
	expDate := float64(c.Expires)
	if session {
		expDate = 0
	}

	return CookieJSON{
		Name:           c.Name,
		Value:          c.Value,
		Domain:         c.Domain,
		Path:           c.Path,
		ExpirationDate: expDate,
		HostOnly:       !strings.HasPrefix(c.Domain, "."),
		HttpOnly:       c.HTTPOnly,
		Secure:         c.Secure,
		Session:        session,
		SameSite:       sameSite,
	}
}

// parseCookieString splits request cookie string headers into cookie structs
func parseCookieString(cookieStr, domain string) []CookieJSON {
	var list []CookieJSON
	parts := strings.Split(cookieStr, ";")
	for _, part := range parts {
		subparts := strings.SplitN(strings.TrimSpace(part), "=", 2)
		if len(subparts) != 2 {
			continue
		}
		name := strings.TrimSpace(subparts[0])
		value := strings.TrimSpace(subparts[1])
		if name == "" {
			continue
		}
		list = append(list, CookieJSON{
			Name:           name,
			Value:          value,
			Domain:         "." + domain,
			Path:           "/",
			ExpirationDate: 0,
			HostOnly:       false,
			HttpOnly:       false,
			Secure:         true,
			Session:        true,
			SameSite:       "lax",
		})
	}
	return list
}

// cookiesToNetscape formats cookies to standard Netscape cookie file format
func cookiesToNetscape(cookies []CookieJSON) string {
	var sb strings.Builder
	sb.WriteString("# Netscape HTTP Cookie File\n# Generated by GoAuto GFX Engine\n\n")
	for _, c := range cookies {
		if c.Name == "" {
			continue
		}
		exp := "0"
		if !c.Session && c.ExpirationDate > 0 {
			exp = fmt.Sprintf("%d", int64(c.ExpirationDate))
		}
		sec := "FALSE"
		if c.Secure {
			sec = "TRUE"
		}
		subdomains := "FALSE"
		if strings.HasPrefix(c.Domain, ".") {
			subdomains = "TRUE"
		}
		sb.WriteString(fmt.Sprintf("%s\t%s\t%s\t%s\t%s\t%s\t%s\n",
			c.Domain, subdomains, c.Path, sec, exp, c.Name, c.Value,
		))
	}
	return sb.String()
}

// cookiesToHeader formats cookies into a single HTTP Header string
func cookiesToHeader(cookies []CookieJSON) string {
	var parts []string
	for _, c := range cookies {
		if c.Name != "" {
			parts = append(parts, fmt.Sprintf("%s=%s", c.Name, c.Value))
		}
	}
	return strings.Join(parts, "; ")
}

// solveCloudflare performs the turnstile solve routine
func solveCloudflare(page *rod.Page) bool {
	info, err := page.Info()
	title, urlStr := "", ""
	if err == nil {
		title = info.Title
		urlStr = info.URL
	}
	log.Printf("[CF] Cloudflare solver triggered. URL: %s | Title: %s", urlStr, title)

	content, _ := page.HTML()
	bodySnippet := ""
	if idx := strings.Index(content, "<body"); idx != -1 {
		bodySnippet = content[idx:]
		if len(bodySnippet) > 1000 {
			bodySnippet = bodySnippet[:1000]
		}
	} else if len(content) > 1000 {
		bodySnippet = content[:1000]
	} else {
		bodySnippet = content
	}
	log.Printf("[CF] Body snippet (truncated): %s", bodySnippet)

	log.Println("[CF] Searching for Cloudflare Turnstile checkbox...")
	var cfFrame *rod.Page
	var iframeSrc string

	iframes, err := page.Elements("iframe")
	if err == nil {
		log.Printf("[CF] Found %d total iframes on page", len(iframes))
		for idx, iframe := range iframes {
			src, err := iframe.Attribute("src")
			srcVal := ""
			if err == nil && src != nil {
				srcVal = *src
			}
			idVal, _ := iframe.Attribute("id")
			classVal, _ := iframe.Attribute("class")
			
			idStr := ""
			if idVal != nil { idStr = *idVal }
			classStr := ""
			if classVal != nil { classStr = *classVal }
			
			log.Printf("[CF] Iframe #%d: src=%s, id=%s, class=%s", idx, srcVal, idStr, classStr)
			
			if strings.Contains(srcVal, "challenges.cloudflare.com") || strings.Contains(srcVal, "cloudflare") {
				cfFrame = iframe.MustFrame()
				iframeSrc = srcVal
			}
		}
	}

	if cfFrame == nil {
		hasCF, el, err := page.Has("iframe[src*='cloudflare'], iframe[src*='challenges']")
		if err == nil && hasCF && el != nil {
			cfFrame = el.MustFrame()
			if src, err := el.Attribute("src"); err == nil && src != nil {
				iframeSrc = *src
			}
		}
	}

	if cfFrame == nil {
		log.Println("[CF] Cloudflare iframe not found.")
		return false
	}

	log.Printf("[CF] Selected Cloudflare iframe: %s", iframeSrc)
	err = cfFrame.Timeout(8 * time.Second).WaitElementsMoreThan("#challenge-stage, .ctp-checkbox-container, input[type='checkbox']", 0)
	if err != nil {
		log.Printf("[CF] Timeout waiting for checkbox elements in iframe: %v", err)
	}

	var rect struct {
		X      float64 `json:"x"`
		Y      float64 `json:"y"`
		Width  float64 `json:"width"`
		Height float64 `json:"height"`
	}
	res, err := cfFrame.Eval(`() => {
		const el = document.querySelector('.ctp-checkbox-container') ||
				   document.querySelector('input[type="checkbox"]') ||
				   document.querySelector('.mark') ||
				   document.querySelector('#challenge-stage');
		if (!el) return null;
		const r = el.getBoundingClientRect();
		return { x: r.left, y: r.top, width: r.width, height: r.height };
	}`)
	if err != nil || res.Value.Nil() {
		log.Println("[CF] Could not locate checkbox bounds in iframe.")
		return false
	}
	_ = res.Value.Unmarshal(&rect)

	var iframeRect struct {
		X float64 `json:"x"`
		Y float64 `json:"y"`
	}
	resParent, err := page.Eval(`(src) => {
		const iframe = document.querySelector('iframe[src="' + src + '"]') ||
		               document.querySelector('iframe[src*="challenges.cloudflare.com"]') ||
		               document.querySelector('iframe[src*="cloudflare"]') ||
		               document.querySelector('iframe');
		if (!iframe) return null;
		const r = iframe.getBoundingClientRect();
		return { x: r.left, y: r.top };
	}`, iframeSrc)
	if err != nil || resParent.Value.Nil() {
		log.Println("[CF] Could not locate iframe bounds in parent page.")
		return false
	}
	_ = resParent.Value.Unmarshal(&iframeRect)

	clickX := iframeRect.X + rect.X + (rect.Width / 2)
	clickY := iframeRect.Y + rect.Y + (rect.Height / 2)
	log.Printf("[CF] Clicking Turnstile checkbox at: x=%f, y=%f", clickX, clickY)

	mouse := page.Mouse
	mouse.MustMoveTo(clickX, clickY)
	time.Sleep(300 * time.Millisecond)
	mouse.MustClick(proto.InputMouseButtonLeft)

	log.Println("[CF] Click performed. Waiting for page reaction...")
	time.Sleep(5 * time.Second)
	return true
}

// takeScreenshot saves a debug screenshot in case of failure
func takeScreenshot(page *rod.Page, label string, dir string) {
	_ = os.MkdirAll(dir, 0755)
	fp := filepath.Join(dir, fmt.Sprintf("%s_%d.png", label, time.Now().Unix()))
	log.Printf("📸 [gfx_keywordtool] Taking screenshot for %s...", label)
	imgBytes, err := page.Timeout(15 * time.Second).Screenshot(false, nil)
	if err == nil {
		_ = os.WriteFile(fp, imgBytes, 0644)
		log.Printf("📸 [gfx_keywordtool] Debug screenshot saved: %s", fp)
		return
	}
	log.Printf("⚠️ [gfx_keywordtool] Failed to save debug screenshot for %s: %v", label, err)
}
