package gfx

func initRegistry() {
	registry = map[string]ToolDef{
	"gfx_oneclick_runVecteezy": {TaskUID: "gfx_oneclick_runVecteezy", Kind: KindOneClick, Name: "Vecteezy", WebsiteID: "vecteezy"},
	"gfx_runAirbrush": {
		TaskUID: "gfx_runAirbrush", Kind: KindExtension,
		Name: "Airbrush",
		ToolURL: "https://app.gfxtoolz.ai/tools/airbrush-ai",
		Selector: "button[data-tool-cookie=\"true\"]",
		FallbackIndex: 0,
		WebsiteID: "airbrush",
		BackupFile: "gfx_airbrush_cookies.json",
		Referer: "https://airbrush.ai/",
		SessionCookieNames: []string{"loginSet"},
		CaptureLocalStorage: true,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
		SkipPageReload: true,
	},
	"gfx_runAnswerthepublic": {
		TaskUID: "gfx_runAnswerthepublic", Kind: KindExtension,
		Name: "Answerthepublic",
		ToolURL: "https://app.gfxtoolz.ai/tools/answerthepublic",
		Selector: "button[data-tool-cookie=\"true\"]",
		FallbackIndex: 0,
		WebsiteID: "answerthepublic",
		BackupFile: "gfx_answerthepublic_cookies.json",
		Referer: "https://answerthepublic.com/",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runAvatarBuilder": {
		TaskUID: "gfx_runAvatarBuilder", Kind: KindExtension,
		Name: "AvatarBuilder",
		ToolURL: "https://app.gfxtoolz.ai/tools/avatar-builder",
		Selector: "button[data-tool-cookie=\"true\"]",
		FallbackIndex: 0,
		WebsiteID: "avatarbuilder",
		BackupFile: "gfx_avatarbuilder_cookies.json",
		Referer: "https://avatarbuilder.com/",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runBlinkist": {
		TaskUID: "gfx_runBlinkist", Kind: KindExtension,
		Name: "Blinkist",
		ToolURL: "https://app.gfxtoolz.ai/tools/blinkist",
		Selector: "button[data-tool-cookie=\"true\"]",
		FallbackIndex: 0,
		WebsiteID: "blinkist",
		BackupFile: "gfx_blinkist_cookies.json",
		Referer: "https://www.blinkist.com/",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runCanva": {
		TaskUID: "gfx_runCanva", Kind: KindExtension,
		Name: "Canva Pro",
		ToolURL: "https://app.gfxtoolz.ai/tools/canva-pro",
		Selector: "button[data-tldr=\"canva77899\"]",
		FallbackIndex: 0,
		WebsiteID: "canva",
		BackupFile: "gfx_canva_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runCanva2": {
		TaskUID: "gfx_runCanva2", Kind: KindExtension,
		Name: "Canva Pro",
		ToolURL: "https://app.gfxtoolz.ai/tools/canva-pro",
		Selector: "button[data-tldr=\"canva77900\"]",
		FallbackIndex: 1,
		WebsiteID: "canva_2",
		BackupFile: "gfx_canva_2_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runCapcut": {
		TaskUID: "gfx_runCapcut", Kind: KindExtension,
		Name: "Capcut",
		ToolURL: "https://app.gfxtoolz.ai/tools/capcut",
		Selector: "button[data-tool-cookie=\"true\"].cookie-btn",
		FallbackIndex: 0,
		WebsiteID: "capcut",
		BackupFile: "gfx_capcut_cookies.json",
		Referer: "https://www.capcut.com/",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runChatgpt": {
		TaskUID: "gfx_runChatgpt", Kind: KindExtension,
		Name: "Chatgpt",
		ToolURL: "https://app.gfxtoolz.ai/tools/chatgpt1",
		Selector: "button[data-tool-cookie=\"true\"].cookie-btn",
		FallbackIndex: 0,
		WebsiteID: "chatgpt",
		BackupFile: "gfx_chatgpt_cookies.json",
		Referer: "https://chatgpt.com/",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runClosercopy": {
		TaskUID: "gfx_runClosercopy", Kind: KindExtension,
		Name: "CloserCopy",
		ToolURL: "https://app.gfxtoolz.ai/tools/closercopy",
		Selector: "button[data-tool-cookie=\"true\"].cookie-btn",
		FallbackIndex: 0,
		WebsiteID: "closercopy",
		BackupFile: "gfx_closercopy_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runCodecademy": {
		TaskUID: "gfx_runCodecademy", Kind: KindExtension,
		Name: "Codecademy",
		ToolURL: "https://app.gfxtoolz.ai/tools/codecademy",
		Selector: "",
		FallbackIndex: 0,
		WebsiteID: "codecademy",
		BackupFile: "gfx_codecademy_cookies.json",
		Referer: "https://www.codecademy.com/catalog",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runCoursera": {
		TaskUID: "gfx_runCoursera", Kind: KindExtension,
		Name: "Coursera",
		ToolURL: "https://app.gfxtoolz.ai/tools/coursera",
		Selector: "button[data-tool-cookie=\"true\"].cookie-btn",
		FallbackIndex: 0,
		WebsiteID: "coursera",
		BackupFile: "gfx_coursera_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runCreativeFabrica": {
		TaskUID: "gfx_runCreativeFabrica", Kind: KindExtension,
		Name: "Creative Fabrica",
		ToolURL: "https://app.gfxtoolz.ai/tools/creative-fabrica",
		Selector: "button[data-tool-cookie=\"true\"].cookie-btn",
		FallbackIndex: 0,
		WebsiteID: "creativefabrica",
		BackupFile: "gfx_creativefabrica_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runCreatorai": {
		TaskUID: "gfx_runCreatorai", Kind: KindExtension,
		Name: "Creator AI",
		ToolURL: "https://app.gfxtoolz.ai/tools/creator-ai",
		Selector: "button[data-tool-cookie=\"true\"].cookie-btn",
		FallbackIndex: 0,
		WebsiteID: "creatorai",
		BackupFile: "gfx_creatorai_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runCreattie": {
		TaskUID: "gfx_runCreattie", Kind: KindExtension,
		Name: "Creattie",
		ToolURL: "https://app.gfxtoolz.ai/tools/creattie-",
		Selector: "button[data-tool-cookie=\"true\"].cookie-btn",
		FallbackIndex: 0,
		WebsiteID: "creattie",
		BackupFile: "gfx_creattie_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runEducative": {
		TaskUID: "gfx_runEducative", Kind: KindExtension,
		Name: "Educative",
		ToolURL: "https://app.gfxtoolz.ai/tools/educative",
		Selector: "button[data-tool-cookie=\"true\"].cookie-btn",
		FallbackIndex: 0,
		WebsiteID: "educative",
		BackupFile: "gfx_educative_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runEnvatoTuts": {
		TaskUID: "gfx_runEnvatoTuts", Kind: KindExtension,
		Name: "Envato Tuts+",
		ToolURL: "https://app.gfxtoolz.ai/tools/envato-tuts",
		Selector: "button[data-tool-cookie=\"true\"].cookie-btn",
		FallbackIndex: 0,
		WebsiteID: "envato_tuts",
		BackupFile: "gfx_envato_tuts_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runEpidemic": {
		TaskUID: "gfx_runEpidemic", Kind: KindExtension,
		Name: "Epidemic Sounds 1",
		ToolURL: "https://app.gfxtoolz.ai/tools/epidemicsounds",
		Selector: "button[data-tool-id=\"tool_1779421133823_7331\"]",
		FallbackIndex: 0,
		WebsiteID: "epidemicsounds",
		BackupFile: "gfx_epidemicsounds_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runEpidemic2": {
		TaskUID: "gfx_runEpidemic2", Kind: KindExtension,
		Name: "Epidemic Sounds 2",
		ToolURL: "https://app.gfxtoolz.ai/tools/epidemicsounds",
		Selector: "button[data-tool-id=\"tool_1779421133728_9224\"]",
		FallbackIndex: 1,
		WebsiteID: "epidemicsounds_2",
		BackupFile: "gfx_epidemicsounds_2_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runEverland": {
		TaskUID: "gfx_runEverland", Kind: KindExtension,
		Name: "Everland",
		ToolURL: "https://app.gfxtoolz.ai/tools/everland",
		Selector: "button[data-tool-id=\"tool_1779422109125_911\"]",
		FallbackIndex: 0,
		WebsiteID: "everland",
		BackupFile: "gfx_everland_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runFlaticon": {
		TaskUID: "gfx_runFlaticon", Kind: KindExtension,
		Name: "Flaticon",
		ToolURL: "https://app.gfxtoolz.ai/tools/flaticon",
		Selector: "button[data-tool-id=\"tool_1779422308506_7481\"]",
		FallbackIndex: 0,
		WebsiteID: "flaticon",
		BackupFile: "gfx_flaticon_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runFomoclips": {
		TaskUID: "gfx_runFomoclips", Kind: KindExtension,
		Name: "FomoClips",
		ToolURL: "https://app.gfxtoolz.ai/tools/fomoclips",
		Selector: "button[data-tool-id=\"tool_1779423166656_822\"]",
		FallbackIndex: 0,
		WebsiteID: "fomoclips",
		BackupFile: "gfx_fomoclips_cookies.json",
		Referer: "https://app.fomoclips.com/app/dashboards/default",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: true,
	},
	"gfx_runFrase": {
		TaskUID: "gfx_runFrase", Kind: KindExtension,
		Name: "Frase",
		ToolURL: "https://app.gfxtoolz.ai/tools/frase-io",
		Selector: "button[data-tool-id=\"tool_1779427385038_1502\"]",
		FallbackIndex: 0,
		WebsiteID: "frase",
		BackupFile: "gfx_frase_cookies.json",
		Referer: "https://app.frase.io/app/home",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: true,
	},
	"gfx_runGlorify": {
		TaskUID: "gfx_runGlorify", Kind: KindExtension,
		Name: "Glorify",
		ToolURL: "https://app.gfxtoolz.ai/tools/glorify",
		Selector: "button[data-tool-id=\"tool_1779427732018_7939\"]",
		FallbackIndex: 0,
		WebsiteID: "glorify",
		BackupFile: "gfx_glorify_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runGptzero": {
		TaskUID: "gfx_runGptzero", Kind: KindExtension,
		Name: "GPTZero",
		ToolURL: "https://app.gfxtoolz.ai/tools/gptzero",
		Selector: "button[data-tool-cookie=\"true\"].ls-btn",
		FallbackIndex: 0,
		WebsiteID: "gptzero",
		BackupFile: "gfx_gptzero_cookies.json",
		Referer: "https://gptzero.me/",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: true,
	},
	"gfx_runGrammarly": {
		TaskUID: "gfx_runGrammarly", Kind: KindExtension,
		Name: "Grammarly",
		ToolURL: "https://app.gfxtoolz.ai/tools/grammerly",
		Selector: "button[data-tool-id=\"tool_1779428472534_6061\"]",
		FallbackIndex: 0,
		WebsiteID: "grammarly",
		BackupFile: "gfx_grammarly_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runGrok": {
		TaskUID: "gfx_runGrok", Kind: KindExtension,
		Name: "Grok 1",
		ToolURL: "https://app.gfxtoolz.ai/tools/grok",
		Selector: "button[data-tool-id=\"tool_1779429696437_1114\"]",
		FallbackIndex: 0,
		WebsiteID: "grok",
		BackupFile: "gfx_grok_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runGrok2": {
		TaskUID: "gfx_runGrok2", Kind: KindExtension,
		Name: "Grok 2",
		ToolURL: "https://app.gfxtoolz.ai/tools/grok",
		Selector: "button[data-tool-id=\"tool_1779429696832_151\"]",
		FallbackIndex: 1,
		WebsiteID: "grok_2",
		BackupFile: "gfx_grok_2_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runHelium10_01": {
		TaskUID: "gfx_runHelium10_01", Kind: KindExtension,
		Name: "Helium 10 Acc 01",
		ToolURL: "https://app.gfxtoolz.ai/tools/helium-10",
		Selector: "button[data-tool-id=\"tool_1779431201481_2839\"]",
		FallbackIndex: 0,
		WebsiteID: "helium10_01",
		BackupFile: "gfx_helium10_01_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runHelium10_02": {
		TaskUID: "gfx_runHelium10_02", Kind: KindExtension,
		Name: "Helium 10 Acc 02",
		ToolURL: "https://app.gfxtoolz.ai/tools/helium-10",
		Selector: "button[data-tool-id=\"tool_1779431201610_6890\"]",
		FallbackIndex: 1,
		WebsiteID: "helium10_02",
		BackupFile: "gfx_helium10_02_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runHixBypass": {
		TaskUID: "gfx_runHixBypass", Kind: KindExtension,
		Name: "Hix AI Bypass AI",
		ToolURL: "https://app.gfxtoolz.ai/tools/hix-ai-bypass-ai",
		Selector: "button[data-tool-id=\"tool_1779441412510_9224\"]",
		FallbackIndex: 0,
		WebsiteID: "hix_bypass",
		BackupFile: "gfx_hix_bypass_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runHumanPal": {
		TaskUID: "gfx_runHumanPal", Kind: KindExtension,
		Name: "HumanPal",
		ToolURL: "https://app.gfxtoolz.ai/tools/humanpal",
		Selector: "button[data-tool-cookie=\"true\"]",
		FallbackIndex: 0,
		WebsiteID: "humanpal",
		BackupFile: "gfx_humanpal_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runIaskai": {
		TaskUID: "gfx_runIaskai", Kind: KindExtension,
		Name: "I Ask AI",
		ToolURL: "https://app.gfxtoolz.ai/tools/i-ask-ai",
		Selector: "button[data-tool-id=\"tool_1779442423733_8974\"]",
		FallbackIndex: 0,
		WebsiteID: "iaskai",
		BackupFile: "gfx_iaskai_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runInvideo": {
		TaskUID: "gfx_runInvideo", Kind: KindExtension,
		Name: "InVideo",
		ToolURL: "https://app.gfxtoolz.ai/tools/invideo",
		Selector: "button[data-tool-id=\"tool_1779443012010_688\"]",
		FallbackIndex: 0,
		WebsiteID: "invideo",
		BackupFile: "gfx_invideo_cookies.json",
		Referer: "https://studio.invideo.io/dashboard",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: true,
	},
	"gfx_runJasper": {
		TaskUID: "gfx_runJasper", Kind: KindExtension,
		Name: "Jasper",
		ToolURL: "https://app.gfxtoolz.ai/tools/jasper-ai",
		Selector: "",
		FallbackIndex: 0,
		WebsiteID: "jasper",
		BackupFile: "gfx_jasper_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runJungleScout": {
		TaskUID: "gfx_runJungleScout", Kind: KindExtension,
		Name: "JungleScout",
		ToolURL: "https://app.gfxtoolz.ai/tools/jungle-scout",
		Selector: "",
		FallbackIndex: 0,
		WebsiteID: "junglescout",
		BackupFile: "gfx_junglescout_cookies.json",
		Referer: "https://www.junglescout.com/",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runKeywordtool": {
		TaskUID: "gfx_runKeywordtool", Kind: KindExtension,
		Name: "Keywordtool",
		ToolURL: "https://app.gfxtoolz.ai/tools/keywordtool-io",
		Selector: "",
		FallbackIndex: 0,
		WebsiteID: "keywordtool",
		BackupFile: "gfx_keywordtool_cookies.json",
		Referer: "https://keywordtool.io/",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runKittl": {
		TaskUID: "gfx_runKittl", Kind: KindExtension,
		Name: "Kittl",
		ToolURL: "https://app.gfxtoolz.ai/tools/kittl",
		Selector: "button[data-tool-id=\"tool_1779446931237_6932\"]",
		FallbackIndex: 0,
		WebsiteID: "kittl",
		BackupFile: "gfx_kittl_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runKwfinder": {
		TaskUID: "gfx_runKwfinder", Kind: KindExtension,
		Name: "KWFinder",
		ToolURL: "https://app.gfxtoolz.ai/tools/kwfinder",
		Selector: "button[data-tool-id=\"tool_1779447336734_3750\"]",
		FallbackIndex: 0,
		WebsiteID: "kwfinder",
		BackupFile: "gfx_kwfinder_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runLeonardo": {
		TaskUID: "gfx_runLeonardo", Kind: KindExtension,
		Name: "Leonardo AI",
		ToolURL: "https://app.gfxtoolz.ai/tools/leonardo-ai",
		Selector: "button[data-tool-cookie=\"true\"]",
		FallbackIndex: 0,
		WebsiteID: "leonardo",
		BackupFile: "gfx_leonardo_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runLinguix": {
		TaskUID: "gfx_runLinguix", Kind: KindExtension,
		Name: "Linguix",
		ToolURL: "https://app.gfxtoolz.ai/tools/linguix",
		Selector: "button[data-tool-id=\"tool_1779448191497_3515\"]",
		FallbackIndex: 0,
		WebsiteID: "linguix",
		BackupFile: "gfx_linguix_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runLinkedinLearning": {
		TaskUID: "gfx_runLinkedinLearning", Kind: KindExtension,
		Name: "LinkedIn Learning",
		ToolURL: "https://app.gfxtoolz.ai/tools/linkedin-learning",
		Selector: "button[data-tool-id=\"tool_1779449273720_9270\"]",
		FallbackIndex: 0,
		WebsiteID: "linkedin-learning",
		BackupFile: "gfx_linkedin_learning_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runLovepik": {
		TaskUID: "gfx_runLovepik", Kind: KindExtension,
		Name: "Lovepik",
		ToolURL: "https://app.gfxtoolz.ai/tools/lovepik",
		Selector: "button[data-tool-id=\"tool_1779449645481_3729\"]",
		FallbackIndex: 0,
		WebsiteID: "lovepik",
		BackupFile: "gfx_lovepik_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runMajestic": {
		TaskUID: "gfx_runMajestic", Kind: KindExtension,
		Name: "Majestic",
		ToolURL: "https://app.gfxtoolz.ai/tools/majestic",
		Selector: "button[data-tool-id=\"tool_1779450200763_493\"]",
		FallbackIndex: 0,
		WebsiteID: "majestic",
		BackupFile: "gfx_majestic_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runMoz_01": {
		TaskUID: "gfx_runMoz_01", Kind: KindExtension,
		Name: "Moz Pro 1",
		ToolURL: "https://app.gfxtoolz.ai/tools/moz-pro",
		Selector: "button[data-tool-cookie=\"true\"]",
		FallbackIndex: 0,
		WebsiteID: "mozpro1",
		BackupFile: "gfx_mozpro1_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runMoz_02": {
		TaskUID: "gfx_runMoz_02", Kind: KindExtension,
		Name: "Moz Pro 2",
		ToolURL: "https://app.gfxtoolz.ai/tools/moz-pro",
		Selector: "button[data-tool-cookie=\"true\"]",
		FallbackIndex: 1,
		WebsiteID: "mozpro2",
		BackupFile: "gfx_mozpro2_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runNetflix_01": {
		TaskUID: "gfx_runNetflix_01", Kind: KindExtension,
		Name: "Netflix 1",
		ToolURL: "https://app.gfxtoolz.ai/tools/netflix",
		Selector: "button[data-tool-cookie=\"true\"]",
		FallbackIndex: 0,
		WebsiteID: "netflix01",
		BackupFile: "gfx_netflix01_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runNetflix_02": {
		TaskUID: "gfx_runNetflix_02", Kind: KindExtension,
		Name: "Netflix 2",
		ToolURL: "https://app.gfxtoolz.ai/tools/netflix",
		Selector: "button[data-tool-cookie=\"true\"]",
		FallbackIndex: 1,
		WebsiteID: "netflix02",
		BackupFile: "gfx_netflix02_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runNeuronwriter_01": {
		TaskUID: "gfx_runNeuronwriter_01", Kind: KindExtension,
		Name: "NeuronWriter 1",
		ToolURL: "https://app.gfxtoolz.ai/tools/neuron-writer",
		Selector: "button[data-tool-cookie=\"true\"]",
		FallbackIndex: 0,
		WebsiteID: "neuronwriter_01",
		BackupFile: "gfx_neuronwriter01_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runNeuronwriter_02": {
		TaskUID: "gfx_runNeuronwriter_02", Kind: KindExtension,
		Name: "NeuronWriter 2",
		ToolURL: "https://app.gfxtoolz.ai/tools/neuron-writer",
		Selector: "button[data-tool-cookie=\"true\"]",
		FallbackIndex: 1,
		WebsiteID: "neuronwriter_02",
		BackupFile: "gfx_neuronwriter02_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runNichess": {
		TaskUID: "gfx_runNichess", Kind: KindExtension,
		Name: "Nichess",
		ToolURL: "https://app.gfxtoolz.ai/tools/nichess",
		Selector: "button.cookie-btn, button[data-tool-cookie=\"true\"]",
		FallbackIndex: 0,
		WebsiteID: "nichess",
		BackupFile: "gfx_nichess_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runNotegpt": {
		TaskUID: "gfx_runNotegpt", Kind: KindExtension,
		Name: "NoteGPT",
		ToolURL: "https://app.gfxtoolz.ai/tools/notegpt",
		Selector: "button[data-tool-id=\"tool_1779462838196_589\"]",
		FallbackIndex: 0,
		WebsiteID: "notegpt",
		BackupFile: "gfx_notegpt_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runOcoya": {
		TaskUID: "gfx_runOcoya", Kind: KindExtension,
		Name: "Ocoya",
		ToolURL: "https://app.gfxtoolz.ai/tools/ocoya",
		Selector: "button[data-tool-id=\"tool_1779279926687_7171\"]",
		FallbackIndex: 0,
		WebsiteID: "ocoya",
		BackupFile: "gfx_ocoya_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runPaperpal": {
		TaskUID: "gfx_runPaperpal", Kind: KindExtension,
		Name: "Paperpal",
		ToolURL: "https://app.gfxtoolz.ai/tools/paperpal",
		Selector: "button[data-tool-id=\"tool_1779288602196_4372\"]",
		FallbackIndex: 0,
		WebsiteID: "paperpal",
		BackupFile: "gfx_paperpal_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runPerplexity": {
		TaskUID: "gfx_runPerplexity", Kind: KindExtension,
		Name: "Perplexity 1",
		ToolURL: "https://app.gfxtoolz.ai/tools/perpexility-ai",
		Selector: "button[data-tool-id=\"tool_1779280714549_2054\"]",
		FallbackIndex: 0,
		WebsiteID: "perplexity",
		BackupFile: "gfx_perplexity_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runPerplexity2": {
		TaskUID: "gfx_runPerplexity2", Kind: KindExtension,
		Name: "Perplexity 2",
		ToolURL: "https://app.gfxtoolz.ai/tools/perpexility-ai",
		Selector: "button[data-tool-id=\"tool_1779280714661_9201\"]",
		FallbackIndex: 1,
		WebsiteID: "perplexity_2",
		BackupFile: "gfx_perplexity2_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runPikmonkey": {
		TaskUID: "gfx_runPikmonkey", Kind: KindExtension,
		Name: "Pikmonkey",
		ToolURL: "https://app.gfxtoolz.ai/tools/pikmonkey",
		Selector: "button[data-tool-id=\"tool_1779290636119_2686\"]",
		FallbackIndex: 0,
		WebsiteID: "pikmonkey",
		BackupFile: "gfx_pikmonkey_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runPlaceit": {
		TaskUID: "gfx_runPlaceit", Kind: KindExtension,
		Name: "Placeit",
		ToolURL: "https://app.gfxtoolz.ai/tools/place-it",
		Selector: "button[data-tool-id=\"tool_1779274000957_4383\"]",
		FallbackIndex: 0,
		WebsiteID: "placeit",
		BackupFile: "gfx_placeit_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runPrezi": {
		TaskUID: "gfx_runPrezi", Kind: KindExtension,
		Name: "Prezi AI",
		ToolURL: "https://app.gfxtoolz.ai/tools/prezi-ai",
		Selector: "button[data-tool-id=\"tool_1779282298379_7730\"]",
		FallbackIndex: 0,
		WebsiteID: "prezi",
		BackupFile: "gfx_prezi_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runPrimeVideo": {
		TaskUID: "gfx_runPrimeVideo", Kind: KindExtension,
		Name: "Prime Video",
		ToolURL: "https://app.gfxtoolz.ai/tools/prime-video",
		Selector: "button[data-tldr=\"primevideo\"]",
		FallbackIndex: 0,
		WebsiteID: "primevideo",
		BackupFile: "gfx_prime_video_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runRelume": {
		TaskUID: "gfx_runRelume", Kind: KindExtension,
		Name: "Relume",
		ToolURL: "https://app.gfxtoolz.ai/tools/relume",
		Selector: "button[data-tool-id=\"tool_1779279927282_4654\"]",
		FallbackIndex: 0,
		WebsiteID: "relume",
		BackupFile: "gfx_relume_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runRenderforest": {
		TaskUID: "gfx_runRenderforest", Kind: KindExtension,
		Name: "Renderforest",
		ToolURL: "https://app.gfxtoolz.ai/tools/renderforest",
		Selector: "button[data-tool-id=\"tool_1779282300144_8914\"]",
		FallbackIndex: 0,
		WebsiteID: "renderforest",
		BackupFile: "gfx_renderforest_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runRewritify": {
		TaskUID: "gfx_runRewritify", Kind: KindExtension,
		Name: "Rewritify AI",
		ToolURL: "https://app.gfxtoolz.ai/tools/rewritify-ai",
		Selector: "button[data-tool-id=\"tool_1779282299269_2958\"]",
		FallbackIndex: 0,
		WebsiteID: "rewritify",
		BackupFile: "gfx_rewritify_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runRivalflow": {
		TaskUID: "gfx_runRivalflow", Kind: KindExtension,
		Name: "Rivalflow",
		ToolURL: "https://app.gfxtoolz.ai/tools/rivalflow",
		Selector: "button[data-tool-id=\"tool_1779287636976_6664\"]",
		FallbackIndex: 0,
		WebsiteID: "rivalflow",
		BackupFile: "gfx_rivalflow_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runRytr": {
		TaskUID: "gfx_runRytr", Kind: KindExtension,
		Name: "Rytr",
		ToolURL: "https://app.gfxtoolz.ai/tools/rytr",
		Selector: "button[data-tool-id=\"tool_1779288601593_4672\"]",
		FallbackIndex: 0,
		WebsiteID: "rytr",
		BackupFile: "gfx_rytr_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runScite": {
		TaskUID: "gfx_runScite", Kind: KindExtension,
		Name: "Scite AI",
		ToolURL: "https://app.gfxtoolz.ai/tools/scite-ai",
		Selector: "button[data-tool-id=\"tool_1779287635649_4339\"]",
		FallbackIndex: 0,
		WebsiteID: "scite",
		BackupFile: "gfx_scite_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runScrepy": {
		TaskUID: "gfx_runScrepy", Kind: KindExtension,
		Name: "Screpy",
		ToolURL: "https://app.gfxtoolz.ai/tools/screpy",
		Selector: "button[data-tool-id=\"tool_1779287635216_8811\"]",
		FallbackIndex: 0,
		WebsiteID: "screpy",
		BackupFile: "gfx_screpy_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runScribd": {
		TaskUID: "gfx_runScribd", Kind: KindExtension,
		Name: "Scribd",
		ToolURL: "https://app.gfxtoolz.ai/tools/scribd",
		Selector: "button[data-tool-id=\"tool_1779289986261_6218\"]",
		FallbackIndex: 0,
		WebsiteID: "scribd",
		BackupFile: "gfx_scribd_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runSellTheTrend": {
		TaskUID: "gfx_runSellTheTrend", Kind: KindExtension,
		Name: "Sell The Trend",
		ToolURL: "https://app.gfxtoolz.ai/tools/sell-the-trend",
		Selector: "button[data-tool-id=\"tool_1779290636026_2355\"]",
		FallbackIndex: 0,
		WebsiteID: "sell_the_trend",
		BackupFile: "gfx_sellthetrend_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runSemrush": {
		TaskUID: "gfx_runSemrush", Kind: KindExtension,
		Name: "Semrush GFX",
		ToolURL: "https://app.gfxtoolz.ai/tools/semrush",
		Selector: "button[data-tool-id=\"tool_1779283061835_4523\"]",
		FallbackIndex: 0,
		WebsiteID: "semrush",
		BackupFile: "gfx_semrush_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runSeositecheckup": {
		TaskUID: "gfx_runSeositecheckup", Kind: KindExtension,
		Name: "SEOSiteCheckup",
		ToolURL: "https://app.gfxtoolz.ai/tools/seositecheckup",
		Selector: "button[data-tool-id=\"tool_1779287627697_24\"]",
		FallbackIndex: 0,
		WebsiteID: "seositecheckup",
		BackupFile: "gfx_seositecheckup_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runSeotesteronline": {
		TaskUID: "gfx_runSeotesteronline", Kind: KindExtension,
		Name: "SEO Tester Online",
		ToolURL: "https://app.gfxtoolz.ai/tools/seotester-online",
		Selector: "[data-tool-id=\"tool_1779287634968_161\"]",
		FallbackIndex: 0,
		WebsiteID: "seotesteronline",
		BackupFile: "gfx_seotesteronline_cookies.json",
		Referer: "https://suite.seotesteronline.com/",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: true,
	},
	"gfx_runSerpstat": {
		TaskUID: "gfx_runSerpstat", Kind: KindExtension,
		Name: "Serpstat",
		ToolURL: "https://app.gfxtoolz.ai/tools/serpstat",
		Selector: "button[data-tool-id=\"tool_1779287630736_3407\"]",
		FallbackIndex: 0,
		WebsiteID: "serpstat",
		BackupFile: "gfx_serpstat_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runShortform": {
		TaskUID: "gfx_runShortform", Kind: KindExtension,
		Name: "Shortform",
		ToolURL: "https://app.gfxtoolz.ai/tools/shortform",
		Selector: "",
		FallbackIndex: 0,
		WebsiteID: "shortform",
		BackupFile: "gfx_shortform_cookies.json",
		Referer: "https://www.shortform.com/",
		SessionCookieNames: nil,
		CaptureLocalStorage: true,
		CaptureIndexedDB: true,
		UseLSPayloadFormat: false,
	},
	"gfx_runSimilarweb": {
		TaskUID: "gfx_runSimilarweb", Kind: KindExtension,
		Name: "Similarweb",
		ToolURL: "https://app.gfxtoolz.ai/tools/similarweb",
		Selector: "button[data-tool-id=\"tool_1779287630433_6767\"]",
		FallbackIndex: 0,
		WebsiteID: "similarweb",
		BackupFile: "gfx_similarweb_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runSkillshare": {
		TaskUID: "gfx_runSkillshare", Kind: KindExtension,
		Name: "Skillshare",
		ToolURL: "https://app.gfxtoolz.ai/tools/skillshare",
		Selector: "button[data-tool-id=\"tool_1779288599037_1975\"]",
		FallbackIndex: 0,
		WebsiteID: "skillshare",
		BackupFile: "gfx_skillshare_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runSlideshare": {
		TaskUID: "gfx_runSlideshare", Kind: KindExtension,
		Name: "Slideshare",
		ToolURL: "https://app.gfxtoolz.ai/tools/slideshare",
		Selector: "button[data-tool-id=\"tool_1779289986077_516\"]",
		FallbackIndex: 0,
		WebsiteID: "slideshare",
		BackupFile: "gfx_slideshare_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runSpamzilla": {
		TaskUID: "gfx_runSpamzilla", Kind: KindExtension,
		Name: "Spamzilla",
		ToolURL: "https://app.gfxtoolz.ai/tools/spamzilla",
		Selector: "button[data-tool-id=\"tool_1779283064169_7229\"]",
		FallbackIndex: 0,
		WebsiteID: "spamzilla",
		BackupFile: "gfx_spamzilla_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runSpyfu": {
		TaskUID: "gfx_runSpyfu", Kind: KindExtension,
		Name: "Spyfu",
		ToolURL: "https://app.gfxtoolz.ai/tools/spyfu",
		Selector: "button[data-tool-id=\"tool_1779283065848_8433\"]",
		FallbackIndex: 0,
		WebsiteID: "spyfu",
		BackupFile: "gfx_spyfu_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runStorybase": {
		TaskUID: "gfx_runStorybase", Kind: KindExtension,
		Name: "Storybase",
		ToolURL: "https://app.gfxtoolz.ai/tools/storybase",
		Selector: "button[data-tool-id=\"tool_1779287637219_901\"]",
		FallbackIndex: 0,
		WebsiteID: "storybase",
		BackupFile: "gfx_storybase_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runSubmagic": {
		TaskUID: "gfx_runSubmagic", Kind: KindExtension,
		Name: "Submagic",
		ToolURL: "https://app.gfxtoolz.ai/tools/submagic-io",
		Selector: "button[data-tool-id=\"tool_1779283061547_8158\"]",
		FallbackIndex: 0,
		WebsiteID: "submagic",
		BackupFile: "gfx_submagic_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runUbersuggest_01": {
		TaskUID: "gfx_runUbersuggest_01", Kind: KindExtension,
		Name: "Ubersuggest Account 1",
		ToolURL: "https://app.gfxtoolz.ai/tools/ubersuggest",
		Selector: "button[data-tool-id=\"tool_1779287633914_6009\"]",
		FallbackIndex: 0,
		WebsiteID: "ubersuggest_01",
		BackupFile: "gfx_ubersuggest_01_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runUbersuggest_02": {
		TaskUID: "gfx_runUbersuggest_02", Kind: KindExtension,
		Name: "Ubersuggest Account 2",
		ToolURL: "https://app.gfxtoolz.ai/tools/ubersuggest",
		Selector: "button[data-tool-id=\"tool_1779287786512_210\"]",
		FallbackIndex: 0,
		WebsiteID: "ubersuggest_02",
		BackupFile: "gfx_ubersuggest_02_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runUdemy_01": {
		TaskUID: "gfx_runUdemy_01", Kind: KindExtension,
		Name: "Udemy Account 1",
		ToolURL: "https://app.gfxtoolz.ai/tools/udemy",
		Selector: "button[data-tool-id=\"tool_1779288594241_8361\"]",
		FallbackIndex: 0,
		WebsiteID: "udemy_01",
		BackupFile: "gfx_udemy_01_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runUdemy_02": {
		TaskUID: "gfx_runUdemy_02", Kind: KindExtension,
		Name: "Udemy Account 2",
		ToolURL: "https://app.gfxtoolz.ai/tools/udemy",
		Selector: "button[data-tool-id=\"tool_1779288595513_346\"]",
		FallbackIndex: 0,
		WebsiteID: "udemy_02",
		BackupFile: "gfx_udemy_02_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runUdemy_03": {
		TaskUID: "gfx_runUdemy_03", Kind: KindExtension,
		Name: "Udemy Account 3",
		ToolURL: "https://app.gfxtoolz.ai/tools/udemy",
		Selector: "button[data-tool-id=\"tool_1779288597413_689\"]",
		FallbackIndex: 0,
		WebsiteID: "udemy_03",
		BackupFile: "gfx_udemy_03_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_runUizard": {
		TaskUID: "gfx_runUizard", Kind: KindExtension,
		Name: "Uizard Pro",
		ToolURL: "https://app.gfxtoolz.ai/tools/uizard-pro",
		Selector: "button[data-tool-id=\"tool_1779279927386_2733\"]",
		FallbackIndex: 0,
		WebsiteID: "uizard",
		BackupFile: "gfx_uizard_cookies.json",
		SessionCookieNames: nil,
		CaptureLocalStorage: false,
		CaptureIndexedDB: false,
		UseLSPayloadFormat: false,
	},
	"gfx_scrapeArtislyAI": {TaskUID: "gfx_scrapeArtislyAI", Kind: KindCredFetch, ScrapeName: "Artisly Ai", ToolURL: "https://app.gfxtoolz.ai/tools/artisly-ai"},
	"gfx_scrapeArtspaceAI": {TaskUID: "gfx_scrapeArtspaceAI", Kind: KindCredFetch, ScrapeName: "Artspace Ai", ToolURL: "https://app.gfxtoolz.ai/tools/artspace-ai"},
	"gfx_scrapeBuzzsumo": {TaskUID: "gfx_scrapeBuzzsumo", Kind: KindCredFetch, ScrapeName: "Buzzsumo", ToolURL: "https://app.gfxtoolz.ai/tools/buzzsumo"},
	"gfx_scrapeCramly": {TaskUID: "gfx_scrapeCramly", Kind: KindCredFetch, ScrapeName: "Cramly AI", ToolURL: "https://app.gfxtoolz.ai/tools/cramly-ai"},
	"gfx_scrapeCrazyeggs": {TaskUID: "gfx_scrapeCrazyeggs", Kind: KindCredFetch, ScrapeName: "Crazyeggs", ToolURL: "https://app.gfxtoolz.ai/tools/crazyeggs"},
	"gfx_scrapeCreatopy": {TaskUID: "gfx_scrapeCreatopy", Kind: KindCredFetch, ScrapeName: "Creatopy", ToolURL: "https://app.gfxtoolz.ai/tools/creatopy-plus"},
	"gfx_scrapeDesignbeast": {TaskUID: "gfx_scrapeDesignbeast", Kind: KindCredFetch, ScrapeName: "Designbest", ToolURL: "https://app.gfxtoolz.ai/tools/designbeast"},
	"gfx_scrapeGptzero": {TaskUID: "gfx_scrapeGptzero", Kind: KindCredFetch, ScrapeName: "Gptzero", ToolURL: "https://app.gfxtoolz.ai/tools/gptzero"},
	"gfx_scrapeKatalistAI": {TaskUID: "gfx_scrapeKatalistAI", Kind: KindCredFetch, ScrapeName: "Katalist Ai", ToolURL: "https://app.gfxtoolz.ai/tools/katalist-ai"},
	"gfx_scrapePodcastleAI": {TaskUID: "gfx_scrapePodcastleAI", Kind: KindCredFetch, ScrapeName: "Podcastle Ai", ToolURL: "https://app.gfxtoolz.ai/tools/podcastle-ai"},
	"gfx_scrapeSlidebeans": {TaskUID: "gfx_scrapeSlidebeans", Kind: KindCredFetch, ScrapeName: "Slidebeans", ToolURL: "https://app.gfxtoolz.ai/tools/slidebeans"},
	"gfx_scrapeToonsAI": {TaskUID: "gfx_scrapeToonsAI", Kind: KindCredFetch, ScrapeName: "Toons AI", ToolURL: "https://app.gfxtoolz.ai/tools/toons-ai"},
	}
}
