package queue

import (
	"context"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/http/cookiejar"
	"net/url"
	"regexp"
	"strings"
	"time"

	"gohttpauto/internal/cookiesession"
	"gohttpauto/internal/db"
)

const userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36"

var (
	loginAttemptRE  = regexp.MustCompile(`(?i)name=["']login_attempt_id["'][^>]*value=["']([^"']+)["']`)
	semrushBtnRE    = regexp.MustCompile(`(?i)href=["']([^"']*semrush\.noxtools\.com/server1\.php[^"']*)["']`)
	amErrorsRE      = regexp.MustCompile(`(?is)class=["']am-errors["'][^>]*>(.*?)</`)
)

type capturedCookies struct{ list []*http.Cookie }

func (cc *capturedCookies) record(resp *http.Response) {
	for _, c := range resp.Cookies() {
		cp := *c
		if cp.Domain == "" {
			cp.Domain = resp.Request.URL.Host
		}
		cc.list = append(cc.list, &cp)
	}
}

type loggingTransport struct{ captured *capturedCookies }

func (t *loggingTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	resp, err := http.DefaultTransport.RoundTrip(req)
	if err == nil {
		t.captured.record(resp)
	}
	return resp, err
}

func runNoxSemrushHTTP() (string, string) {
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	var email, password string
	err := db.DB.QueryRowContext(ctx,
		`SELECT username, password_enc FROM credentials WHERE website_id='noxtools' AND is_enabled=1`).
		Scan(&email, &password)
	if err != nil {
		return "failed", "noxtools credentials not found in database"
	}

	jar, _ := cookiejar.New(nil)
	cc := &capturedCookies{}
	client := &http.Client{
		Timeout: 60 * time.Second, Jar: jar,
		Transport: &loggingTransport{captured: cc},
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			if len(via) >= 12 {
				return fmt.Errorf("too many redirects")
			}
			return nil
		},
	}

	// Step 1: login page
	loginURL := "https://noxtools.com/secure/login"
	body, status, err := httpGET(client, loginURL, nil)
	if err != nil || status != 200 {
		return "failed", fmt.Sprintf("login page error: %v", err)
	}
	attemptID, err := parseAttemptID(body)
	if err != nil {
		return "failed", err.Error()
	}

	// Step 2: POST login
	form := url.Values{}
	form.Set("amember_login", email)
	form.Set("amember_pass", password)
	form.Set("login_attempt_id", attemptID)
	form.Set("_referer", "https://noxtools.com/")
	finalURL, postBody, _, err := httpPOST(client, loginURL, form.Encode(), map[string]string{
		"Content-Type": "application/x-www-form-urlencoded",
		"Origin":       "https://noxtools.com",
		"Referer":      loginURL,
	})
	if err != nil || !loginOK(finalURL, postBody) {
		return "failed", "noxtools login failed"
	}

	// Step 3: semrush page
	semPage := "https://noxtools.com/secure/page/semrush"
	semBody, _, err := httpGET(client, semPage, map[string]string{"Referer": "https://noxtools.com/secure/secure/yourwallet"})
	if err != nil {
		return "failed", "semrush page error"
	}
	btn := findSemrushBtn(semBody)
	if btn == "" {
		return "failed", "semrush button not found"
	}
	if strings.HasPrefix(btn, "/") {
		btn = "https://noxtools.com" + btn
	}

	// Step 4: access semrush
	finalSemURL, _, err := httpGET(client, btn, map[string]string{"Referer": semPage})
	if err != nil {
		return "failed", "semrush access error: " + err.Error()
	}
	if !strings.Contains(finalSemURL, "semrush.com.in") {
		log.Printf("⚠️ final URL: %s", finalSemURL)
	}

	// Step 5: extract proxy_token
	token := extractProxyToken(jar, cc.list)
	if token == "" {
		return "failed", "proxy_token cookie not captured"
	}

	netscape := fmt.Sprintf("# Netscape HTTP Cookie File\n# Generated by GoHttpAuto HTTP Engine\n\n.semrush.com.in\tTRUE\t/\tTRUE\t%d\tproxy_token\t%s\n",
		time.Now().Add(365*24*time.Hour).Unix(), token)

	expires := time.Now().Add(365 * 24 * time.Hour)
	cookies := []cookiesession.Cookie{
		cookiesession.SimpleCookie(".semrush.com.in", "proxy_token", token, true, true, expires),
	}
	err = cookiesession.Save(ctx, cookiesession.SaveOptions{
		WebsiteID: "nox",
		Referer:   "https://www.semrush.com/",
		Cookies:   cookies,
		Netscape:  netscape,
	})
	if err != nil {
		return "failed", "db save error: " + err.Error()
	}

	// Upload to refs
	go uploadNoxCookies(netscape)

	return "success", "HTTP automation complete — proxy_token captured"
}

func extractProxyToken(jar http.CookieJar, captured []*http.Cookie) string {
	for _, c := range captured {
		if c.Name == "proxy_token" && strings.Contains(strings.ToLower(c.Domain), "semrush") {
			return c.Value
		}
	}
	for _, h := range []string{"https://1.semrush.com.in/", "https://semrush.com.in/"} {
		u, _ := url.Parse(h)
		for _, c := range jar.Cookies(u) {
			if c.Name == "proxy_token" {
				return c.Value
			}
		}
	}
	return ""
}

func uploadNoxCookies(netscape string) {
	data := url.Values{}
	data.Set("cookies", netscape)
	data.Set("update", "Update Cookies")
	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.PostForm("https://refs.1clkaccess.store/nxsm1.php", data)
	if err != nil {
		log.Printf("⚠️ nxsm1 upload failed: %v", err)
		return
	}
	resp.Body.Close()
}

func httpGET(client *http.Client, rawURL string, extra map[string]string) (string, int, error) {
	req, _ := http.NewRequest(http.MethodGet, rawURL, nil)
	req.Header.Set("User-Agent", userAgent)
	req.Header.Set("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
	for k, v := range extra {
		req.Header.Set(k, v)
	}
	resp, err := client.Do(req)
	if err != nil {
		return "", 0, err
	}
	defer resp.Body.Close()
	data, _ := io.ReadAll(io.LimitReader(resp.Body, 4<<20))
	return string(data), resp.StatusCode, nil
}

func httpPOST(client *http.Client, rawURL, body string, extra map[string]string) (string, string, int, error) {
	req, _ := http.NewRequest(http.MethodPost, rawURL, strings.NewReader(body))
	req.Header.Set("User-Agent", userAgent)
	req.Header.Set("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
	for k, v := range extra {
		req.Header.Set(k, v)
	}
	resp, err := client.Do(req)
	if err != nil {
		return "", "", 0, err
	}
	defer resp.Body.Close()
	data, _ := io.ReadAll(io.LimitReader(resp.Body, 4<<20))
	return resp.Request.URL.String(), string(data), resp.StatusCode, nil
}

func parseAttemptID(html string) (string, error) {
	if m := loginAttemptRE.FindStringSubmatch(html); len(m) > 1 {
		return strings.TrimSpace(m[1]), nil
	}
	return "", fmt.Errorf("login_attempt_id not found")
}

func loginOK(finalURL, body string) bool {
	if amErrorsRE.FindStringSubmatch(body) != nil {
		return false
	}
	return !strings.Contains(strings.ToLower(body), `name="amember_login"`) ||
		!strings.HasSuffix(strings.ToLower(finalURL), "/secure/login")
}

func findSemrushBtn(html string) string {
	if m := semrushBtnRE.FindStringSubmatch(html); len(m) > 1 {
		return strings.TrimSpace(m[1])
	}
	return ""
}
