package nox

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"net/url"
	"strings"
	"time"

	"gohttpauto/internal/automation/portalchrome"
	"gohttpauto/internal/cookiesession"
	"gohttpauto/internal/db"

	"github.com/go-rod/rod"
)

// RunSemrush logs into NoxTools and captures Semrush proxy_token — all in visible Chrome.
func RunSemrush() (string, string) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	var email, password string
	err := db.DB.QueryRowContext(ctx,
		`SELECT username, password_enc FROM credentials WHERE website_id='noxtools' AND is_enabled=1`).
		Scan(&email, &password)
	if err != nil {
		return "failed", "noxtools credentials not found in database"
	}

	sess, err := portalchrome.OpenLoggedIn(ctx, email, password, portalchrome.SessionConfig{
		Tag:             "[Nox]",
		Profile:         "noxtools",
		MemberURL:       "https://noxtools.com/secure/member",
		LoginURL:        "https://noxtools.com/secure/login",
		CookieURL:       "https://noxtools.com/",
		DomainFilter:    "noxtools.com",
		PortalSessionID: "noxtools_login",
		ShowBrowser:     true,
		HeadlessEnv:     "NOX_HEADLESS",
		KeepOpenEnv:     "NOX_KEEP_OPEN",
	})
	if err != nil {
		return "failed", "noxtools portal login failed: " + err.Error()
	}
	defer sess.Close()

	page := sess.Page
	browser := sess.Browser

	log.Println("[Nox] navigating to semrush tool page...")
	if err := page.Timeout(30*time.Second).Navigate("https://noxtools.com/secure/page/semrush"); err != nil {
		return "failed", "semrush page navigation failed: " + err.Error()
	}
	time.Sleep(5 * time.Second)

	btnHref := findSemrushBtnHref(page)
	if btnHref == "" {
		return "failed", "semrush server button not found on page"
	}
	log.Printf("[Nox] semrush link: %s", btnHref)

	newPage := browser.MustPage("")
	if err := newPage.Timeout(60*time.Second).Navigate(btnHref); err != nil {
		return "failed", "semrush access navigation failed: " + err.Error()
	}

	redirected := false
	for w := 0; w < 18; w++ {
		time.Sleep(5 * time.Second)
		info, _ := newPage.Info()
		u := ""
		if info != nil {
			u = info.URL
		}
		log.Printf("[Nox] redirect %d/18: %s", w+1, u)
		if strings.Contains(u, "semrush.com.in") {
			redirected = true
			break
		}
	}
	if !redirected {
		return "failed", "redirect to semrush.com.in timed out"
	}
	time.Sleep(5 * time.Second)

	raw, err := newPage.Cookies([]string{})
	if err != nil {
		return "failed", "cookie read failed: " + err.Error()
	}

	token := ""
	for _, c := range raw {
		if c.Name == "proxy_token" && strings.Contains(strings.ToLower(c.Domain), "semrush") {
			token = c.Value
			break
		}
	}
	if token == "" {
		return "failed", "proxy_token cookie not captured in browser"
	}

	netscape := fmt.Sprintf("# Netscape HTTP Cookie File\n# Generated by GoHttpAuto Nox Chrome\n\n.semrush.com.in\tTRUE\t/\tTRUE\t%d\tproxy_token\t%s\n",
		time.Now().Add(365*24*time.Hour).Unix(), token)

	expires := time.Now().Add(365 * 24 * time.Hour)
	cookies := []cookiesession.Cookie{
		cookiesession.SimpleCookie(".semrush.com.in", "proxy_token", token, true, true, expires),
	}
	if err := cookiesession.Save(ctx, cookiesession.SaveOptions{
		WebsiteID: "nox",
		Referer:   "https://www.semrush.com/",
		Cookies:   cookies,
		Netscape:  netscape,
	}); err != nil {
		return "failed", "db save error: " + err.Error()
	}

	go uploadCookies(netscape)
	return "success", "Chrome automation — proxy_token captured"
}

func findSemrushBtnHref(page *rod.Page) string {
	selectors := []string{
		`a[href*="semrush.noxtools.com/server1"]`,
		`a[href*="semrush.noxtools.com"]`,
	}
	for _, sel := range selectors {
		has, el, err := page.Has(sel)
		if err == nil && has && el != nil {
			if href, err := el.Attribute("href"); err == nil && href != nil && *href != "" {
				return *href
			}
		}
	}
	elements, _ := page.Elements("a")
	for _, el := range elements {
		href, err := el.Attribute("href")
		if err != nil || href == nil {
			continue
		}
		h := *href
		if strings.Contains(h, "semrush") && (strings.Contains(h, "server1") || strings.Contains(h, "noxtools")) {
			return h
		}
	}
	return ""
}

func uploadCookies(netscape string) {
	data := url.Values{}
	data.Set("cookies", netscape)
	data.Set("update", "Update Cookies")
	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.PostForm("https://refs.1clkaccess.store/nxsm1.php", data)
	if err != nil {
		log.Printf("⚠️ [Nox] nxsm1 upload failed: %v", err)
		return
	}
	resp.Body.Close()
}
