package nox

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"net/url"
	"regexp"
	"strings"
	"time"

	"gohttpauto/internal/automation/httpclient"
	"gohttpauto/internal/automation/portalchrome"
	"gohttpauto/internal/cookiesession"
	"gohttpauto/internal/db"
)

var semrushBtnRE = regexp.MustCompile(`(?i)href=["']([^"']*semrush\.noxtools\.com/server1\.php[^"']*)["']`)

// RunSemrush logs into NoxTools via Chrome (Cloudflare-safe) and captures Semrush cookies over HTTP.
func RunSemrush() (string, string) {
	ctx, cancel := context.WithTimeout(context.Background(), 4*time.Minute)
	defer cancel()

	var email, password string
	err := db.DB.QueryRowContext(ctx,
		`SELECT username, password_enc FROM credentials WHERE website_id='noxtools' AND is_enabled=1`).
		Scan(&email, &password)
	if err != nil {
		return "failed", "noxtools credentials not found in database"
	}

	client := httpclient.New(60 * time.Second)
	portalSessionID := "noxtools_login"
	if err := portalchrome.EnsureSession(ctx, client, email, password, portalchrome.SessionConfig{
		Tag:             "[Nox]",
		Profile:         "noxtools",
		MemberURL:       "https://noxtools.com/secure/member",
		LoginURL:        "https://noxtools.com/secure/login",
		CookieURL:       "https://noxtools.com/",
		DomainFilter:    "noxtools.com",
		PortalSessionID: portalSessionID,
		VisibleEnv:      "NOX_VISIBLE",
	}); err != nil {
		return "failed", "noxtools portal login failed: " + err.Error()
	}

	semPage := "https://noxtools.com/secure/page/semrush"
	semBody, _, _, err := client.GET(semPage, map[string]string{"Referer": "https://noxtools.com/secure/secure/yourwallet"})
	if err != nil {
		return "failed", "semrush page error"
	}
	if httpclient.IsCloudflareChallenge(semBody) {
		return "failed", "semrush page blocked by Cloudflare after login"
	}
	btn := findSemrushBtn(semBody)
	if btn == "" {
		return "failed", "semrush button not found"
	}
	if strings.HasPrefix(btn, "/") {
		btn = "https://noxtools.com" + btn
	}

	finalSemURL, _, _, err := client.GET(btn, map[string]string{"Referer": semPage})
	if err != nil {
		return "failed", "semrush access error: " + err.Error()
	}
	if !strings.Contains(finalSemURL, "semrush.com.in") {
		log.Printf("⚠️ [Nox] final URL: %s", finalSemURL)
	}

	token := extractProxyToken(client.HTTP.Jar, client.Captured)
	if token == "" {
		return "failed", "proxy_token cookie not captured"
	}

	netscape := fmt.Sprintf("# Netscape HTTP Cookie File\n# Generated by GoHttpAuto HTTP Engine\n\n.semrush.com.in\tTRUE\t/\tTRUE\t%d\tproxy_token\t%s\n",
		time.Now().Add(365*24*time.Hour).Unix(), token)

	expires := time.Now().Add(365 * 24 * time.Hour)
	cookies := []cookiesession.Cookie{
		cookiesession.SimpleCookie(".semrush.com.in", "proxy_token", token, true, true, expires),
	}
	err = cookiesession.Save(ctx, cookiesession.SaveOptions{
		WebsiteID: "nox",
		Referer:   "https://www.semrush.com/",
		Cookies:   cookies,
		Netscape:  netscape,
	})
	if err != nil {
		return "failed", "db save error: " + err.Error()
	}

	go uploadCookies(netscape)
	return "success", "Chrome login + HTTP capture — proxy_token updated"
}

func extractProxyToken(jar http.CookieJar, captured []*http.Cookie) string {
	for _, c := range captured {
		if c.Name == "proxy_token" && strings.Contains(strings.ToLower(c.Domain), "semrush") {
			return c.Value
		}
	}
	for _, h := range []string{"https://1.semrush.com.in/", "https://semrush.com.in/"} {
		u, _ := url.Parse(h)
		for _, c := range jar.Cookies(u) {
			if c.Name == "proxy_token" {
				return c.Value
			}
		}
	}
	return ""
}

func findSemrushBtn(html string) string {
	if m := semrushBtnRE.FindStringSubmatch(html); len(m) > 1 {
		return strings.TrimSpace(m[1])
	}
	return ""
}

func uploadCookies(netscape string) {
	data := url.Values{}
	data.Set("cookies", netscape)
	data.Set("update", "Update Cookies")
	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.PostForm("https://refs.1clkaccess.store/nxsm1.php", data)
	if err != nil {
		log.Printf("⚠️ [Nox] nxsm1 upload failed: %v", err)
		return
	}
	resp.Body.Close()
}
