package nox

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"net/url"
	"regexp"
	"strings"
	"time"

	"gohttpauto/internal/automation/httpclient"
	"gohttpauto/internal/cookiesession"
	"gohttpauto/internal/db"
)

var semrushBtnRE = regexp.MustCompile(`(?i)href=["']([^"']*semrush\.noxtools\.com/server1\.php[^"']*)["']`)

// RunSemrush logs into NoxTools and captures Semrush proxy_token cookie.
func RunSemrush() (string, string) {
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	var email, password string
	err := db.DB.QueryRowContext(ctx,
		`SELECT username, password_enc FROM credentials WHERE website_id='noxtools' AND is_enabled=1`).
		Scan(&email, &password)
	if err != nil {
		return "failed", "noxtools credentials not found in database"
	}

	client := httpclient.New(60 * time.Second)
	portalSessionID := "noxtools_login"
	if saved, err := cookiesession.Load(ctx, portalSessionID); err == nil && len(saved) > 0 {
		_ = client.SetCookies("https://noxtools.com/", cookiesession.ToHTTPCookies(saved))
		log.Printf("[Nox] restored %d portal cookies", len(saved))
	}

	loginURL := "https://noxtools.com/secure/login"
	body, status, _, err := client.GET(loginURL, nil)
	if err != nil || status != 200 {
		return "failed", fmt.Sprintf("login page error: %v", err)
	}

	needsLogin := strings.Contains(strings.ToLower(body), `name="amember_login"`) ||
		strings.Contains(strings.ToLower(body), `id="amember-login"`)
	if needsLogin {
		attemptID, err := httpclient.ParseAttemptID(body)
		if err != nil {
			return "failed", err.Error()
		}

		form := url.Values{}
		form.Set("amember_login", email)
		form.Set("amember_pass", password)
		form.Set("login_attempt_id", attemptID)
		form.Set("_referer", "https://noxtools.com/")
		finalURL, postBody, _, err := client.POST(loginURL, form.Encode(), map[string]string{
			"Content-Type": "application/x-www-form-urlencoded",
			"Origin":       "https://noxtools.com",
			"Referer":      loginURL,
		})
		if err != nil || !noxLoginOK(finalURL, postBody) {
			return "failed", "noxtools login failed"
		}
	}
	if err := savePortalSession(ctx, client, portalSessionID, "https://noxtools.com/"); err != nil {
		log.Printf("⚠️ [Nox] portal cookie save failed: %v", err)
	}

	semPage := "https://noxtools.com/secure/page/semrush"
	semBody, _, _, err := client.GET(semPage, map[string]string{"Referer": "https://noxtools.com/secure/secure/yourwallet"})
	if err != nil {
		return "failed", "semrush page error"
	}
	btn := findSemrushBtn(semBody)
	if btn == "" {
		return "failed", "semrush button not found"
	}
	if strings.HasPrefix(btn, "/") {
		btn = "https://noxtools.com" + btn
	}

	finalSemURL, _, _, err := client.GET(btn, map[string]string{"Referer": semPage})
	if err != nil {
		return "failed", "semrush access error: " + err.Error()
	}
	if !strings.Contains(finalSemURL, "semrush.com.in") {
		log.Printf("⚠️ [Nox] final URL: %s", finalSemURL)
	}

	token := extractProxyToken(client.HTTP.Jar, client.Captured)
	if token == "" {
		return "failed", "proxy_token cookie not captured"
	}

	netscape := fmt.Sprintf("# Netscape HTTP Cookie File\n# Generated by GoHttpAuto HTTP Engine\n\n.semrush.com.in\tTRUE\t/\tTRUE\t%d\tproxy_token\t%s\n",
		time.Now().Add(365*24*time.Hour).Unix(), token)

	expires := time.Now().Add(365 * 24 * time.Hour)
	cookies := []cookiesession.Cookie{
		cookiesession.SimpleCookie(".semrush.com.in", "proxy_token", token, true, true, expires),
	}
	err = cookiesession.Save(ctx, cookiesession.SaveOptions{
		WebsiteID: "nox",
		Referer:   "https://www.semrush.com/",
		Cookies:   cookies,
		Netscape:  netscape,
	})
	if err != nil {
		return "failed", "db save error: " + err.Error()
	}

	go uploadCookies(netscape)
	return "success", "HTTP automation complete — proxy_token captured"
}

func noxLoginOK(finalURL, body string) bool {
	if !httpclient.LoginOK(finalURL, body) {
		return false
	}
	return !strings.Contains(strings.ToLower(body), `name="amember_login"`) ||
		!strings.HasSuffix(strings.ToLower(finalURL), "/secure/login")
}

func extractProxyToken(jar http.CookieJar, captured []*http.Cookie) string {
	for _, c := range captured {
		if c.Name == "proxy_token" && strings.Contains(strings.ToLower(c.Domain), "semrush") {
			return c.Value
		}
	}
	for _, h := range []string{"https://1.semrush.com.in/", "https://semrush.com.in/"} {
		u, _ := url.Parse(h)
		for _, c := range jar.Cookies(u) {
			if c.Name == "proxy_token" {
				return c.Value
			}
		}
	}
	return ""
}

func findSemrushBtn(html string) string {
	if m := semrushBtnRE.FindStringSubmatch(html); len(m) > 1 {
		return strings.TrimSpace(m[1])
	}
	return ""
}

func uploadCookies(netscape string) {
	data := url.Values{}
	data.Set("cookies", netscape)
	data.Set("update", "Update Cookies")
	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.PostForm("https://refs.1clkaccess.store/nxsm1.php", data)
	if err != nil {
		log.Printf("⚠️ [Nox] nxsm1 upload failed: %v", err)
		return
	}
	resp.Body.Close()
}

func savePortalSession(ctx context.Context, client *httpclient.Client, websiteID, referer string) error {
	raw, err := client.CookiesFor(referer)
	if err != nil {
		return err
	}
	cookies := make([]cookiesession.Cookie, 0, len(raw))
	for _, c := range raw {
		if c == nil || c.Name == "" {
			continue
		}
		exp := c.Expires
		if exp.IsZero() {
			exp = time.Now().Add(24 * time.Hour)
		}
		cookies = append(cookies, cookiesession.SimpleCookie(c.Domain, c.Name, c.Value, c.Secure, c.HttpOnly, exp))
	}
	if len(cookies) == 0 {
		return nil
	}
	return cookiesession.Save(ctx, cookiesession.SaveOptions{
		WebsiteID: websiteID,
		Referer:   referer,
		Cookies:   cookies,
	})
}
