package azad

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"net/url"
	"runtime"
	"strings"
	"time"

	"gohttpauto/internal/automation/portalchrome"
	"gohttpauto/internal/cookiesession"
	"gohttpauto/internal/db"
)

// RunSemrush logs into Azad and captures Semrush proxy cookies — all in visible Chrome.
func RunSemrush() (string, string) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	var username, password string
	err := db.DB.QueryRowContext(ctx,
		`SELECT username, password_enc FROM credentials WHERE website_id='azadseo' AND is_enabled=1`).
		Scan(&username, &password)
	if err != nil {
		return "failed", "azadseo credentials not found in database"
	}

	memberURL := "https://members.azadseo.com/member"
	sess, err := portalchrome.OpenLoggedIn(ctx, username, password, portalchrome.SessionConfig{
		Tag:             "[Azad]",
		Profile:         "azadseo",
		MemberURL:       memberURL,
		LoginURL:        "https://members.azadseo.com/login",
		CookieURL:       "https://members.azadseo.com/",
		DomainFilter:    "azadseo.com",
		PortalSessionID: "azadseo_login",
		ShowBrowser:     runtime.GOOS == "darwin",
		HeadlessEnv:     "AZAD_HEADLESS",
		KeepOpenEnv:     "AZAD_KEEP_OPEN",
	})
	if err != nil {
		return "failed", "azadseo portal login failed: " + err.Error()
	}
	defer sess.Close()

	page := sess.Page
	browser := sess.Browser

	log.Println("[Azad] locating semrush access link on dashboard...")
	var btnHref string
	for i := 0; i < 15; i++ {
		has, el, err := page.Has(`a[href*="semrush2"], a[href*="xemrush.click"]`)
		if err == nil && has && el != nil {
			if href, err := el.Attribute("href"); err == nil && href != nil {
				btnHref = *href
				break
			}
		}
		elements, _ := page.Elements("a")
		for _, el := range elements {
			href, err := el.Attribute("href")
			if err != nil || href == nil {
				continue
			}
			h := strings.ToLower(*href)
			if strings.Contains(h, "semrush2") || strings.Contains(h, "xemrush.click") {
				btnHref = *href
				break
			}
		}
		if btnHref != "" {
			break
		}
		time.Sleep(1 * time.Second)
	}
	if btnHref == "" {
		return "failed", "semrush access link not found on dashboard"
	}
	if strings.HasPrefix(btnHref, "/") {
		btnHref = "https://members.azadseo.com" + btnHref
	}
	log.Printf("[Azad] semrush link: %s", btnHref)

	newPage := browser.MustPage("")
	if err := newPage.Timeout(60*time.Second).Navigate(btnHref); err != nil {
		return "failed", "semrush access navigation failed: " + err.Error()
	}

	hasProxy := false
	for w := 0; w < 30; w++ {
		raw, err := newPage.Cookies([]string{})
		if err == nil {
			for _, c := range raw {
				n := strings.ToLower(c.Name)
				if n == "cf_clearance" || n == "proxy_token" || n == "is_unique" || strings.HasPrefix(n, "_cf") {
					hasProxy = true
					break
				}
			}
		}
		if hasProxy {
			break
		}
		time.Sleep(500 * time.Millisecond)
	}
	time.Sleep(5 * time.Second)

	raw, err := newPage.Cookies([]string{})
	if err != nil {
		return "failed", "cookie read failed: " + err.Error()
	}

	var stored []cookiesession.Cookie
	expires := time.Now().Add(365 * 24 * time.Hour)
	for _, c := range raw {
		if strings.Contains(strings.ToLower(c.Name), "amember") {
			continue
		}
		if c.Name == "" {
			continue
		}
		stored = append(stored, cookiesession.SimpleCookie(
			".xemrush.click", c.Name, c.Value, c.Secure, c.HTTPOnly, expires,
		))
	}
	if len(stored) == 0 {
		return "failed", "no semrush proxy cookies captured in browser"
	}

	netscape := cookiesession.BuildNetscape(stored, "Generated by GoHttpAuto Azad Chrome")
	if err := cookiesession.Save(ctx, cookiesession.SaveOptions{
		WebsiteID: "azad",
		Referer:   "https://semrush2.xemrush.click/",
		Cookies:   stored,
		Netscape:  netscape,
	}); err != nil {
		return "failed", "db save error: " + err.Error()
	}

	go uploadCookies(netscape)
	return "success", fmt.Sprintf("Chrome automation — %d cookies captured", len(stored))
}

const azadUploadURL = "https://refs.1clkaccess.store/azsm2.php"

func uploadCookies(netscape string) {
	data := url.Values{}
	data.Set("cookies", netscape)
	data.Set("update", "Update Cookies")
	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.PostForm(azadUploadURL, data)
	if err != nil {
		log.Printf("⚠️ [Azad] azsm2 upload failed: %v", err)
		return
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusOK {
		log.Printf("✅ [Azad] cookies synced to %s", azadUploadURL)
	}
}
