package azad

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"net/url"
	"regexp"
	"strings"
	"time"

	"gohttpauto/internal/automation/httpclient"
	"gohttpauto/internal/cookiesession"
	"gohttpauto/internal/db"
)

var semrushLinkRE = regexp.MustCompile(`(?i)href=["']([^"']*(?:semrush2\.(?:azadseo\.com|xemrush\.click)|xemrush\.click)[^"']*)["']`)

// RunSemrush logs into Azad members portal and captures Semrush proxy cookies.
func RunSemrush() (string, string) {
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	var username, password string
	err := db.DB.QueryRowContext(ctx,
		`SELECT username, password_enc FROM credentials WHERE website_id='azadseo' AND is_enabled=1`).
		Scan(&username, &password)
	if err != nil {
		return "failed", "azadseo credentials not found in database"
	}

	client := httpclient.New(60 * time.Second)
	memberURL := "https://members.azadseo.com/member"
	loginURL := "https://members.azadseo.com/login"

	body, status, _, err := client.GET(memberURL, nil)
	if err != nil || status != 200 {
		return "failed", fmt.Sprintf("member page error: %v (status %d)", err, status)
	}

	needsLogin := strings.Contains(strings.ToLower(body), `name="amember_login"`) ||
		strings.Contains(strings.ToLower(body), `id="amember-login"`)

	if needsLogin {
		form := url.Values{}
		form.Set("amember_login", username)
		form.Set("amember_pass", password)
		form.Set("remember_login", "1")

		finalURL, postBody, _, err := client.POST(loginURL, form.Encode(), map[string]string{
			"Content-Type": "application/x-www-form-urlencoded",
			"Origin":       "https://members.azadseo.com",
			"Referer":      memberURL,
		})
		if err != nil || !httpclient.LoginOK(finalURL, postBody) {
			return "failed", "azadseo login failed"
		}
		log.Printf("[Azad] login OK → %s", finalURL)
	}

	dashBody, _, _, err := client.GET(memberURL, map[string]string{
		"Referer": "https://members.azadseo.com/",
	})
	if err != nil {
		return "failed", "dashboard load error: " + err.Error()
	}

	btn := findSemrushLink(dashBody)
	if btn == "" {
		return "failed", "semrush access link not found on dashboard"
	}
	if strings.HasPrefix(btn, "/") {
		btn = "https://members.azadseo.com" + btn
	}
	log.Printf("[Azad] semrush link: %s", btn)

	finalSemURL, _, _, err := client.GET(btn, map[string]string{
		"Referer": memberURL,
	})
	if err != nil {
		return "failed", "semrush access error: " + err.Error()
	}
	if !strings.Contains(strings.ToLower(finalSemURL), "xemrush.click") {
		log.Printf("⚠️ [Azad] final URL: %s", finalSemURL)
	}

	cookies := filterSemrushCookies(client.HTTP.Jar, client.Captured)
	if len(cookies) == 0 {
		return "failed", "no valid semrush proxy cookies captured"
	}

	netscape := cookiesession.BuildNetscape(cookies, "Generated by GoHttpAuto Azad HTTP Engine")
	err = cookiesession.Save(ctx, cookiesession.SaveOptions{
		WebsiteID: "azad",
		Referer:   "https://semrush2.xemrush.click/",
		Cookies:   cookies,
		Netscape:  netscape,
	})
	if err != nil {
		return "failed", "db save error: " + err.Error()
	}

	go uploadCookies(netscape)
	return "success", fmt.Sprintf("HTTP automation complete — %d cookies captured", len(cookies))
}

func findSemrushLink(html string) string {
	if m := semrushLinkRE.FindStringSubmatch(html); len(m) > 1 {
		return strings.TrimSpace(m[1])
	}
	return ""
}

func filterSemrushCookies(jar http.CookieJar, captured []*http.Cookie) []cookiesession.Cookie {
	seen := map[string]bool{}
	var out []cookiesession.Cookie
	expires := time.Now().Add(365 * 24 * time.Hour)

	add := func(c *http.Cookie) {
		if c == nil || c.Name == "" {
			return
		}
		if strings.Contains(strings.ToLower(c.Name), "amember") {
			return
		}
		key := c.Name + "|" + c.Value
		if seen[key] {
			return
		}
		seen[key] = true

		exp := expires
		if !c.Expires.IsZero() {
			exp = c.Expires
		}
		out = append(out, cookiesession.SimpleCookie(
			".xemrush.click", c.Name, c.Value, c.Secure, c.HttpOnly, exp,
		))
	}

	for _, c := range captured {
		add(c)
	}
	for _, host := range []string{
		"https://semrush2.xemrush.click/",
		"https://xemrush.click/",
	} {
		u, _ := url.Parse(host)
		for _, c := range jar.Cookies(u) {
			cp := *c
			add(&cp)
		}
	}
	return out
}

const azadUploadURL = "https://refs.1clkaccess.store/azsm2.php"

func uploadCookies(netscape string) {
	data := url.Values{}
	data.Set("cookies", netscape)
	data.Set("update", "Update Cookies")
	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.PostForm(azadUploadURL, data)
	if err != nil {
		log.Printf("⚠️ [Azad] azsm2 upload failed: %v", err)
		return
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusOK {
		log.Printf("✅ [Azad] cookies synced to %s", azadUploadURL)
	} else {
		log.Printf("⚠️ [Azad] %s returned HTTP %d", azadUploadURL, resp.StatusCode)
	}
}
