package dbseed

// GFXTasks seeded from goauto registry (auto-generated).
var GFXTasks = []TaskDef{
	{UID: "gfx_oneclick_runVecteezy", Name: "Vecteezy (GFX OneClick)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runAirbrush", Name: "Airbrush AI (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runAnswerthepublic", Name: "AnswerThePublic (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runAvatarBuilder", Name: "Avatar Builder (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runBlinkist", Name: "Blinkist (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runCanva", Name: "Canva Pro (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runCanva2", Name: "Canva Pro 2 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runCapcut", Name: "CapCut (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runChatgpt", Name: "ChatGPT (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runClosercopy", Name: "CloserCopy (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runCodecademy", Name: "Codecademy (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runCoursera", Name: "Coursera (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runCreativeFabrica", Name: "Creative Fabrica (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runCreatorai", Name: "Creator AI (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runCreattie", Name: "Creattie (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runEducative", Name: "Educative (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runEnvatoTuts", Name: "Envato Tuts+ (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runEpidemic", Name: "Epidemic Sounds 1 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runEpidemic2", Name: "Epidemic Sounds 2 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runEverland", Name: "Everland (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runFlaticon", Name: "Flaticon (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runFomoclips", Name: "FomoClips (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runFrase", Name: "Frase.io (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runGlorify", Name: "Glorify (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runGptzero", Name: "GPTZero (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runGrammarly", Name: "Grammarly (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runGrok", Name: "Grok 1 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runGrok2", Name: "Grok 2 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runHelium10_01", Name: "Helium 10 Acc 01 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runHelium10_02", Name: "Helium 10 Acc 02 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runHixBypass", Name: "Hix AI Bypass AI (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runHumanPal", Name: "HumanPal (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runIaskai", Name: "I Ask AI (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runInvideo", Name: "InVideo (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runJasper", Name: "Jasper AI (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runJungleScout", Name: "Jungle Scout (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runKeywordtool", Name: "KeywordTool.io (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runKittl", Name: "Kittl (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runKwfinder", Name: "KWFinder (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runLeonardo", Name: "Leonardo AI (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runLinguix", Name: "Linguix (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runLinkedinLearning", Name: "LinkedIn Learning (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runLovepik", Name: "Lovepik (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runMajestic", Name: "Majestic (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runMoz_01", Name: "Moz Pro 1 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runMoz_02", Name: "Moz Pro 2 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runNetflix_01", Name: "Netflix 1 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runNetflix_02", Name: "Netflix 2 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runNeuronwriter_01", Name: "NeuronWriter 1 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runNeuronwriter_02", Name: "NeuronWriter 2 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runNichess", Name: "Nichess (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runNotegpt", Name: "NoteGPT (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runOcoya", Name: "Ocoya (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runPaperpal", Name: "Paperpal (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runPerplexity", Name: "Perplexity 1 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runPerplexity2", Name: "Perplexity 2 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runPikmonkey", Name: "Pikmonkey (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runPlaceit", Name: "Placeit (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runPrezi", Name: "Prezi AI (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runPrimeVideo", Name: "Prime Video (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runRelume", Name: "Relume (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runRenderforest", Name: "Renderforest (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runRewritify", Name: "Rewritify AI (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runRivalflow", Name: "Rivalflow (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runRytr", Name: "Rytr (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runScite", Name: "Scite AI (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runScrepy", Name: "Screpy (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runScribd", Name: "Scribd (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runSellTheTrend", Name: "Sell The Trend (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runSemrush", Name: "Semrush (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runSeositecheckup", Name: "SEOSiteCheckup (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runSeotesteronline", Name: "SEO Tester Online (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runSerpstat", Name: "Serpstat (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runShortform", Name: "Shortform (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runSimilarweb", Name: "Similarweb (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runSkillshare", Name: "Skillshare (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runSlideshare", Name: "Slideshare (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runSpamzilla", Name: "Spamzilla (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runSpyfu", Name: "Spyfu (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runStorybase", Name: "Storybase (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runSubmagic", Name: "Submagic.io (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runUbersuggest_01", Name: "Ubersuggest 1 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runUbersuggest_02", Name: "Ubersuggest 2 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runUdemy_01", Name: "Udemy 1 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runUdemy_02", Name: "Udemy 2 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runUdemy_03", Name: "Udemy 3 (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_runUizard", Name: "Uizard Pro (GFX)", Group: "gfx", AutomationType: "chrome_extension", IntervalMin: 60},
	{UID: "gfx_scrapeArtislyAI", Name: "Scrape Artisly AI (GFX)", Group: "gfx", AutomationType: "cred_fetch", IntervalMin: 180},
	{UID: "gfx_scrapeArtspaceAI", Name: "Scrape Artspace AI (GFX)", Group: "gfx", AutomationType: "cred_fetch", IntervalMin: 180},
	{UID: "gfx_scrapeBuzzsumo", Name: "Scrape Buzzsumo (GFX)", Group: "gfx", AutomationType: "cred_fetch", IntervalMin: 180},
	{UID: "gfx_scrapeCramly", Name: "Scrape Cramly AI (GFX)", Group: "gfx", AutomationType: "cred_fetch", IntervalMin: 180},
	{UID: "gfx_scrapeCrazyeggs", Name: "Scrape Crazyeggs (GFX)", Group: "gfx", AutomationType: "cred_fetch", IntervalMin: 180},
	{UID: "gfx_scrapeCreatopy", Name: "Scrape Creatopy (GFX)", Group: "gfx", AutomationType: "cred_fetch", IntervalMin: 180},
	{UID: "gfx_scrapeDesignbeast", Name: "Scrape Designbest (GFX)", Group: "gfx", AutomationType: "cred_fetch", IntervalMin: 180},
	{UID: "gfx_scrapeGptzero", Name: "Scrape GPTZero (GFX)", Group: "gfx", AutomationType: "cred_fetch", IntervalMin: 180},
	{UID: "gfx_scrapeKatalistAI", Name: "Scrape Katalist AI (GFX)", Group: "gfx", AutomationType: "cred_fetch", IntervalMin: 180},
	{UID: "gfx_scrapePodcastleAI", Name: "Scrape Podcastle AI (GFX)", Group: "gfx", AutomationType: "cred_fetch", IntervalMin: 180},
	{UID: "gfx_scrapeSlidebeans", Name: "Scrape Slidebeans (GFX)", Group: "gfx", AutomationType: "cred_fetch", IntervalMin: 180},
	{UID: "gfx_scrapeToonsAI", Name: "Scrape Toons AI (GFX)", Group: "gfx", AutomationType: "cred_fetch", IntervalMin: 180},
}
